root_dir: "~/.uni/repo/gitea"

container_name: gitea

volume_name: container_gitea

container_dir: "{{ root_dir }}/container"

container_compose_file: "{{ container_dir }}/docker-compose.yml"

UID: 1000
GID: "{{ UID }}"

container_gitea_image: docker.io/gitea/gitea  #:latest
container_mysql_image: docker.io/library/mysql:8
