---
# from: https://docs.gitea.com/installation/install-with-docker

- name: Create directory for Gitea
  ansible.builtin.file:
    path: "{{ docker_dir }}"
    state: directory

- name: Template docker-compose.yml
  ansible.builtin.template:
    src: "gitea-{{ database }}.yml.j2"
    dest: "{{ docker_compose_file }}"