# If not Named_volumes
- name: Create directory for Docker volume
  ansible.builtin.file:
    path: "{{ container_dir }}/gitea"
    state: directory
    owner: "{{ UID }}"
    group: "{{ GID }}"
  when: not Named_volumes