---
# from: https://docs.gitea.com/installation/install-with-docker

- name: Create directory for Gitea
  ansible.builtin.file:
    path: "{{ container_dir }}"
    state: directory

- name: Template docker-compose.yml
  ansible.builtin.template:
    src: "compose file/gitea-{{ database }}.yml.j2"
    dest: "{{ container_compose_file }}"

- name: Is container running?
  ansible.builtin.include_tasks: "../_fn/tasks/is_running.yml"

- name: Podman-compose
  ansible.builtin.shell: podman-compose up -d
  args:
    chdir: "{{ container_dir }}"
  when: is_up.rc