- name: Is container running?
  ansible.builtin.include_tasks: "../_fn/tasks/is_running.yml"

- name: Podman-compose Down
  ansible.builtin.shell: podman-compose down
  args:
    chdir: "{{ container_dir }}"
  when: is_up.rc == 0
  notify: Podman Delete volume
